name: Update Totals

# */20 9-21 * * *

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 9-21 * * *" # every 20m from 9am-9pm

permissions:
  contents: write

jobs:
  update-totals:
    name: Update Totals
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.13
          cache: pip

      - name: Install Python Dependencies
        shell: bash
        run: pip install -r requirements.txt

      - name: Run Python Script
        shell: bash
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          touch .env
          python3 fetch_data.py
          ls -al .env
          if [ -s .env ]; then gh secret set -f .env; fi

      - name: Push Updates
        run: |
          git config user.name 'Bribs'
          git config user.email "<>"
          git commit -am "update data" || true
          git push || true