name: Update Totals

on:
  workflow_dispatch:

jobs:
  update-totals:
    name: Update Totals
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.13
          cache: pip

      - name: Install Python Dependencies
        shell: bash
        run: pip install -r requirements.txt

      - name: Run Python Script
        shell: bash
        run: python3 fetch_data.py